import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, CircleAlert, FileCheck2, ShieldCheck, X } from 'lucide-react';
import { api } from '../lib/api';

type Consent={id:string,code:string,title:string,description:string,purpose_text:string,legal_basis:string,blocking:boolean,withdrawable:boolean,status:string,use_case:string,version:string,validity_period_days:number|null,data_fields:any,downstream_actions:any,regulations:any[]};

export function ConsentDrawer({employeeId, consents, onChange, onClose}:{employeeId:string,consents:Consent[],onChange:()=>void,onClose:()=>void}){
 const [selected,setSelected]=useState<Consent|null>(null); const [busy,setBusy]=useState(false); const [filter,setFilter]=useState('ALL');
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(selected)setSelected(null);else onClose();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[selected,onClose]);
 const filtered=useMemo(()=>consents.filter(c=>filter==='ALL'||(filter==='PENDING'?c.status==='PENDING':filter==='GRANTED'?c.status==='GRANTED':c.status==='WITHDRAWN')),[consents,filter]);
 const act=async(action:'grant'|'acknowledge'|'deny'|'withdraw')=>{if(!selected||!employeeId)return;setBusy(true);try{await api(`/api/employees/${employeeId}/consents/${selected.id}/${action}`,{method:'POST',body:JSON.stringify({method:selected.legal_basis==='NOTICE_ONLY'?'NOTICE_ACKNOWLEDGEMENT':'EXPLICIT_CHECKBOX'})});setSelected(null);onChange()}finally{setBusy(false)}};
 return <div className="modal-backdrop consent-cockpit-backdrop" onClick={onClose}>
  <div className="consent-panel" onClick={e=>e.stopPropagation()}>
   <div className="panel-head"><div><div className="eyebrow">PRIVACY CONTROL PLANE</div><h2>Consent cockpit</h2><p>{employeeId?'Purpose-specific processing controls linked to this employee record.':'Active policy catalog that will attach to this record at creation.'}</p></div><div className="head-actions"><ShieldCheck size={28}/><button className="icon-btn" onClick={onClose} aria-label="Close consent cockpit"><X/></button></div></div>
   <div className="filter-row">{['ALL','PENDING','GRANTED','WITHDRAWN'].map(x=><button key={x} className={filter===x?'filter active':'filter'} onClick={()=>setFilter(x)}>{x}</button>)}</div>
   {!filtered.length?<div className="consent-empty"><ShieldCheck size={22}/><strong>No {filter==='ALL'?'consent':filter.toLowerCase()} records</strong><p>{employeeId?'Consent/notice records for this employee appear here once the readiness engine maps purposes to the record.':'No active policies are configured in this tenant yet.'}</p></div>:<div className="consent-list">{filtered.map(c=><button key={c.id} className="consent-card" onClick={()=>setSelected(c)}><div className="consent-icon">{c.status==='GRANTED'?<Check/>:<FileCheck2/>}</div><div className="consent-main"><strong>{c.title}</strong><span>{c.use_case}</span><small>{c.legal_basis} · v{c.version}</small></div><div className={`status ${c.status.toLowerCase()}`}>{c.status}</div><ChevronRight/></button>)}</div>}
  </div>
  {selected&&<div className="modal-backdrop" onClick={e=>{e.stopPropagation();setSelected(null)}}><div className="consent-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">CONSENT / NOTICE DETAIL</div><h3>{selected.title}</h3></div><button className="icon-btn" onClick={()=>setSelected(null)}><X/></button></div><p>{selected.description}</p><div className="detail-grid"><div><label>Purpose</label><p>{selected.purpose_text}</p></div><div><label>Legal basis</label><p>{selected.legal_basis}</p></div><div><label>Data covered</label><p>{Array.isArray(selected.data_fields)?selected.data_fields.join(', '):JSON.stringify(selected.data_fields)}</p></div><div><label>Use case</label><p>{selected.use_case}</p></div></div><div className="regulation-strip"><CircleAlert size={18}/><div><strong>Jurisdiction mapping</strong><p>{selected.regulations?.length || 0} configured regulation mappings. Validate applicability before production.</p></div></div><div className="modal-actions"><button className="ghost" onClick={()=>setSelected(null)}>Close</button>{employeeId?selected.status==='GRANTED'&&selected.withdrawable?<button className="danger" disabled={busy} onClick={()=>act('withdraw')}>Withdraw</button>:selected.status!=='GRANTED'?<><button className="ghost" disabled={busy} onClick={()=>act(selected.legal_basis==='NOTICE_ONLY'?'acknowledge':'deny')}>{selected.legal_basis==='NOTICE_ONLY'?'Acknowledge notice':'Deny'}</button>{selected.legal_basis!=='NOTICE_ONLY'&&<button className="primary" disabled={busy} onClick={()=>act('grant')}>Grant processing</button>}</>:null:null}</div></div></div>}
 </div>;
}