import { z } from 'zod';

export const employeeSchema = z.object({
  employeeCode: z.string().min(1).max(20),
  firstName: z.string().min(1).max(50),
  middleName: z.string().max(50).optional().nullable(),
  lastName: z.string().min(1).max(50),
  displayName: z.string().max(100).optional().nullable(),
  dateOfBirth: z.string(),
  gender: z.enum(['MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY']),
  maritalStatus: z.enum(['SINGLE','MARRIED','DIVORCED','WIDOWED']).optional().nullable(),
  bloodGroup: z.string().max(5).optional().nullable(),
  nationality: z.string().min(1).max(50).default('India'),
  aadhaar: z.string().regex(/^\d{12}$/).optional().nullable(),
  pan: z.string().regex(/^[A-Z]{5}[0-9]{4}[A-Z]$/).optional().nullable(),
  passportNumber: z.string().max(20).optional().nullable(),
  passportExpiry: z.string().optional().nullable(),
  photographUrl: z.string().url().optional().nullable(),
  disabilityFlag: z.boolean().default(false),
  disabilityType: z.string().max(100).optional().nullable(),
  religion: z.string().max(50).optional().nullable(),
  governmentCategory: z.string().max(20).optional().nullable(),
  bloodDonor: z.boolean().default(false),
  organDonor: z.boolean().default(false),
  personalMobile: z.string().min(7).max(20),
  personalEmail: z.string().email(),
  officialEmail: z.string().email().optional().nullable(),
  officialMobile: z.string().max(20).optional().nullable(),
  emergencyContactName: z.string().min(1).max(100),
  emergencyContactNumber: z.string().min(7).max(20),
  emergencyContactRelation: z.string().max(40).optional().nullable(),
  currentAddress: z.object({line1:z.string().min(1),line2:z.string().optional().nullable(),city:z.string().min(1),stateCode:z.string().min(2),pincode:z.string().min(4),countryCode:z.string().length(2),proofType:z.string().optional().nullable(),since:z.string().optional().nullable()}),
  permanentAddress: z.object({line1:z.string().min(1),line2:z.string().optional().nullable(),city:z.string().min(1),stateCode:z.string().min(2),pincode:z.string().min(4),countryCode:z.string().length(2),proofType:z.string().optional().nullable(),since:z.string().optional().nullable()}),
  job: z.object({
    employmentType: z.enum(['PERMANENT','CONTRACT','INTERN','CONSULTANT','PROBATION','TRAINEE']),
    employeeCategory: z.enum(['WHITE_COLLAR','BLUE_COLLAR','FIELD','WORK_FROM_HOME']).optional().nullable(),
    dateOfJoining: z.string(),
    confirmationDate: z.string().optional().nullable(),
    probationMonths: z.number().int().nonnegative().optional().nullable(),
    status: z.enum(['ACTIVE','ON_NOTICE','RESIGNED','TERMINATED','RETIRED','INACTIVE','ON_LONG_LEAVE']),
    workLocationId: z.string().uuid().optional().nullable(),
    workLocationType: z.enum(['OFFICE','REMOTE','HYBRID','CLIENT_SITE']).optional().nullable(),
    reportingManagerId: z.string().uuid().optional().nullable(),
    designationId: z.string().uuid().optional().nullable(),
    gradeId: z.string().uuid().optional().nullable(),
    departmentId: z.string().uuid().optional().nullable(),
    subDepartment: z.string().optional().nullable(),
    costCenterId: z.string().uuid().optional().nullable(),
    businessUnit: z.string().optional().nullable(),
    shiftId: z.string().uuid().optional().nullable(),
    weeklyOffs: z.array(z.string()).default(['SUNDAY']),
    dateOfExit: z.string().optional().nullable(),
    exitReason: z.string().optional().nullable(),
    rehireEligible: z.boolean().default(true),
    attendanceTrackingMode: z.string().default('WEB'),
    noticePeriodDays: z.number().int().nonnegative().optional().nullable()
  }),
  statutory: z.object({uanNumber:z.string().max(12).optional().nullable(),pfNumber:z.string().optional().nullable(),pfApplicable:z.boolean(),pfJoiningDate:z.string().optional().nullable(),esicNumber:z.string().max(10).optional().nullable(),esiApplicable:z.boolean(),ptState:z.string().optional().nullable(),ptRegistrationNumber:z.string().optional().nullable(),lwfApplicable:z.boolean(),taxRegime:z.enum(['OLD','NEW']),panVerified:z.boolean(),aadhaarPanLinked:z.boolean(),taxDeclarationStatus:z.string(),form16DeliveryMode:z.string().optional().nullable(),nominationUnderEpfDone:z.boolean(),epsMember:z.boolean(),epsPreviousMemberId:z.string().optional().nullable(),internationalWorkerFlag:z.boolean(),passportCountryOfOrigin:z.string().optional().nullable(),wcPolicyCategory:z.string().optional().nullable(),esicDispensary:z.string().optional().nullable()}),
  bank: z.object({bankName:z.string(),accountNumber:z.string(),ifscCode:z.string().regex(/^[A-Z]{4}0[A-Z0-9]{6}$/i),bankBranch:z.string().optional().nullable(),accountHolderName:z.string(),accountType:z.enum(['SAVINGS','CURRENT']),salaryPaymentMode:z.enum(['BANK_TRANSFER','CHEQUE','CASH']),upiId:z.string().optional().nullable(),pennyDropVerified:z.boolean()}),
  family: z.array(z.object({memberName:z.string(),relationship:z.string(),dateOfBirth:z.string().optional().nullable(),isDependent:z.boolean(),dependentForInsurance:z.boolean(),aadhaar:z.string().optional().nullable(),nomineeFlag:z.boolean(),nominationSharePercent:z.number().min(0).max(100).optional().nullable(),guardianName:z.string().optional().nullable()})),
  education: z.array(z.object({highestQualification:z.string().optional().nullable(),specialization:z.string().optional().nullable(),institution:z.string().optional().nullable(),yearOfPassing:z.number().int().optional().nullable(),gradeOrPercentage:z.number().optional().nullable()})),
  skills: z.array(z.string()),
  certifications: z.array(z.object({name:z.string(),issuer:z.string().optional().nullable(),issuedOn:z.string().optional().nullable(),expiresOn:z.string().optional().nullable(),credentialId:z.string().optional().nullable()})),
  languages: z.array(z.object({languageName:z.string(),canRead:z.boolean(),canWrite:z.boolean(),canSpeak:z.boolean()})),
  experience: z.array(z.object({previousEmployerName:z.string(),designation:z.string().optional().nullable(),fromDate:z.string().optional().nullable(),toDate:z.string().optional().nullable(),lastDrawnSalary:z.number().optional().nullable(),reasonForLeaving:z.string().optional().nullable(),previousPfNumber:z.string().optional().nullable(),relievingLetterReceived:z.boolean()})),
  role: z.string().min(1),
  mfaEnabled: z.boolean().default(false)
});

export const consentActionSchema = z.object({
  method: z.enum(['EXPLICIT_CHECKBOX','OTP','DIGITAL_SIGNATURE','GUARDIAN','NOTICE_ACKNOWLEDGEMENT','VERBAL_RECORDED']).optional(),
  reason: z.string().max(500).optional(),
  evidenceObjectKey: z.string().optional(),
  guardianId: z.string().uuid().optional(),
  deviceInfo: z.record(z.any()).optional(),
  geoLocation: z.record(z.any()).optional()
});
